#!/bin/bash

# Exit on error
set -e

# Validate that oc is installed. oc is required instead of kubectl because of
# the 'oc adm certificate' subcommand.
oc version > /dev/null
if [[ $? != 0 ]] ; then
    echo "ERROR: Command 'oc' not found in PATH"
    exit 1
fi

# Get list of pending status CSRs
PENDING_CSRS=$(oc --insecure-skip-tls-verify=true get csr \
    -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}')

# If found, approve all pending CSRs
if [[ -z "$PENDING_CSRS" ]] ; then
    echo 'No pending CSRs to approve!'
else
    oc --insecure-skip-tls-verify=true adm certificate approve $PENDING_CSRS
fi
